/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TrackActivity200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrackActivity200Response{}

// TrackActivity200Response struct for TrackActivity200Response
type TrackActivity200Response struct {
	Message string `json:"message"`
}

type _TrackActivity200Response TrackActivity200Response

// NewTrackActivity200Response instantiates a new TrackActivity200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrackActivity200Response(message string) *TrackActivity200Response {
	this := TrackActivity200Response{}
	this.Message = message
	return &this
}

// NewTrackActivity200ResponseWithDefaults instantiates a new TrackActivity200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrackActivity200ResponseWithDefaults() *TrackActivity200Response {
	this := TrackActivity200Response{}
	return &this
}

// GetMessage returns the Message field value
func (o *TrackActivity200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *TrackActivity200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *TrackActivity200Response) SetMessage(v string) {
	o.Message = v
}

func (o TrackActivity200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrackActivity200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *TrackActivity200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTrackActivity200Response := _TrackActivity200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTrackActivity200Response)

	if err != nil {
		return err
	}

	*o = TrackActivity200Response(varTrackActivity200Response)

	return err
}

type NullableTrackActivity200Response struct {
	value *TrackActivity200Response
	isSet bool
}

func (v NullableTrackActivity200Response) Get() *TrackActivity200Response {
	return v.value
}

func (v *NullableTrackActivity200Response) Set(val *TrackActivity200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackActivity200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackActivity200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackActivity200Response(val *TrackActivity200Response) *NullableTrackActivity200Response {
	return &NullableTrackActivity200Response{value: val, isSet: true}
}

func (v NullableTrackActivity200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackActivity200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


