/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CreateQuestScheduleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateQuestScheduleRequest{}

// CreateQuestScheduleRequest struct for CreateQuestScheduleRequest
type CreateQuestScheduleRequest struct {
	Recurring bool `json:"recurring"`
	QuestId string `json:"questId"`
	EndTime time.Time `json:"endTime"`
	StartTime time.Time `json:"startTime"`
}

type _CreateQuestScheduleRequest CreateQuestScheduleRequest

// NewCreateQuestScheduleRequest instantiates a new CreateQuestScheduleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateQuestScheduleRequest(recurring bool, questId string, endTime time.Time, startTime time.Time) *CreateQuestScheduleRequest {
	this := CreateQuestScheduleRequest{}
	this.Recurring = recurring
	this.QuestId = questId
	this.EndTime = endTime
	this.StartTime = startTime
	return &this
}

// NewCreateQuestScheduleRequestWithDefaults instantiates a new CreateQuestScheduleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateQuestScheduleRequestWithDefaults() *CreateQuestScheduleRequest {
	this := CreateQuestScheduleRequest{}
	return &this
}

// GetRecurring returns the Recurring field value
func (o *CreateQuestScheduleRequest) GetRecurring() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Recurring
}

// GetRecurringOk returns a tuple with the Recurring field value
// and a boolean to check if the value has been set.
func (o *CreateQuestScheduleRequest) GetRecurringOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recurring, true
}

// SetRecurring sets field value
func (o *CreateQuestScheduleRequest) SetRecurring(v bool) {
	o.Recurring = v
}

// GetQuestId returns the QuestId field value
func (o *CreateQuestScheduleRequest) GetQuestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuestId
}

// GetQuestIdOk returns a tuple with the QuestId field value
// and a boolean to check if the value has been set.
func (o *CreateQuestScheduleRequest) GetQuestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestId, true
}

// SetQuestId sets field value
func (o *CreateQuestScheduleRequest) SetQuestId(v string) {
	o.QuestId = v
}

// GetEndTime returns the EndTime field value
func (o *CreateQuestScheduleRequest) GetEndTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *CreateQuestScheduleRequest) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *CreateQuestScheduleRequest) SetEndTime(v time.Time) {
	o.EndTime = v
}

// GetStartTime returns the StartTime field value
func (o *CreateQuestScheduleRequest) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *CreateQuestScheduleRequest) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *CreateQuestScheduleRequest) SetStartTime(v time.Time) {
	o.StartTime = v
}

func (o CreateQuestScheduleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateQuestScheduleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["recurring"] = o.Recurring
	toSerialize["questId"] = o.QuestId
	toSerialize["endTime"] = o.EndTime
	toSerialize["startTime"] = o.StartTime
	return toSerialize, nil
}

func (o *CreateQuestScheduleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recurring",
		"questId",
		"endTime",
		"startTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateQuestScheduleRequest := _CreateQuestScheduleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateQuestScheduleRequest)

	if err != nil {
		return err
	}

	*o = CreateQuestScheduleRequest(varCreateQuestScheduleRequest)

	return err
}

type NullableCreateQuestScheduleRequest struct {
	value *CreateQuestScheduleRequest
	isSet bool
}

func (v NullableCreateQuestScheduleRequest) Get() *CreateQuestScheduleRequest {
	return v.value
}

func (v *NullableCreateQuestScheduleRequest) Set(val *CreateQuestScheduleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateQuestScheduleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateQuestScheduleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateQuestScheduleRequest(val *CreateQuestScheduleRequest) *NullableCreateQuestScheduleRequest {
	return &NullableCreateQuestScheduleRequest{value: val, isSet: true}
}

func (v NullableCreateQuestScheduleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateQuestScheduleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


