/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QuestUpdateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuestUpdateInput{}

// QuestUpdateInput struct for QuestUpdateInput
type QuestUpdateInput struct {
	Type QuestType `json:"type"`
	Description string `json:"description"`
	Title string `json:"title"`
	QuestId string `json:"questId"`
}

type _QuestUpdateInput QuestUpdateInput

// NewQuestUpdateInput instantiates a new QuestUpdateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuestUpdateInput(type_ QuestType, description string, title string, questId string) *QuestUpdateInput {
	this := QuestUpdateInput{}
	this.Type = type_
	this.Description = description
	this.Title = title
	this.QuestId = questId
	return &this
}

// NewQuestUpdateInputWithDefaults instantiates a new QuestUpdateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuestUpdateInputWithDefaults() *QuestUpdateInput {
	this := QuestUpdateInput{}
	return &this
}

// GetType returns the Type field value
func (o *QuestUpdateInput) GetType() QuestType {
	if o == nil {
		var ret QuestType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *QuestUpdateInput) GetTypeOk() (*QuestType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *QuestUpdateInput) SetType(v QuestType) {
	o.Type = v
}

// GetDescription returns the Description field value
func (o *QuestUpdateInput) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *QuestUpdateInput) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *QuestUpdateInput) SetDescription(v string) {
	o.Description = v
}

// GetTitle returns the Title field value
func (o *QuestUpdateInput) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *QuestUpdateInput) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *QuestUpdateInput) SetTitle(v string) {
	o.Title = v
}

// GetQuestId returns the QuestId field value
func (o *QuestUpdateInput) GetQuestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuestId
}

// GetQuestIdOk returns a tuple with the QuestId field value
// and a boolean to check if the value has been set.
func (o *QuestUpdateInput) GetQuestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestId, true
}

// SetQuestId sets field value
func (o *QuestUpdateInput) SetQuestId(v string) {
	o.QuestId = v
}

func (o QuestUpdateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuestUpdateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["description"] = o.Description
	toSerialize["title"] = o.Title
	toSerialize["questId"] = o.QuestId
	return toSerialize, nil
}

func (o *QuestUpdateInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"description",
		"title",
		"questId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuestUpdateInput := _QuestUpdateInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuestUpdateInput)

	if err != nil {
		return err
	}

	*o = QuestUpdateInput(varQuestUpdateInput)

	return err
}

type NullableQuestUpdateInput struct {
	value *QuestUpdateInput
	isSet bool
}

func (v NullableQuestUpdateInput) Get() *QuestUpdateInput {
	return v.value
}

func (v *NullableQuestUpdateInput) Set(val *QuestUpdateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableQuestUpdateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableQuestUpdateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuestUpdateInput(val *QuestUpdateInput) *NullableQuestUpdateInput {
	return &NullableQuestUpdateInput{value: val, isSet: true}
}

func (v NullableQuestUpdateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuestUpdateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


