/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the QuestScheduleCreateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuestScheduleCreateInput{}

// QuestScheduleCreateInput struct for QuestScheduleCreateInput
type QuestScheduleCreateInput struct {
	Recurring *bool `json:"recurring,omitempty"`
	QuestId string `json:"questId"`
	EndTime time.Time `json:"endTime"`
	StartTime time.Time `json:"startTime"`
}

type _QuestScheduleCreateInput QuestScheduleCreateInput

// NewQuestScheduleCreateInput instantiates a new QuestScheduleCreateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuestScheduleCreateInput(questId string, endTime time.Time, startTime time.Time) *QuestScheduleCreateInput {
	this := QuestScheduleCreateInput{}
	this.QuestId = questId
	this.EndTime = endTime
	this.StartTime = startTime
	return &this
}

// NewQuestScheduleCreateInputWithDefaults instantiates a new QuestScheduleCreateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuestScheduleCreateInputWithDefaults() *QuestScheduleCreateInput {
	this := QuestScheduleCreateInput{}
	return &this
}

// GetRecurring returns the Recurring field value if set, zero value otherwise.
func (o *QuestScheduleCreateInput) GetRecurring() bool {
	if o == nil || IsNil(o.Recurring) {
		var ret bool
		return ret
	}
	return *o.Recurring
}

// GetRecurringOk returns a tuple with the Recurring field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QuestScheduleCreateInput) GetRecurringOk() (*bool, bool) {
	if o == nil || IsNil(o.Recurring) {
		return nil, false
	}
	return o.Recurring, true
}

// HasRecurring returns a boolean if a field has been set.
func (o *QuestScheduleCreateInput) HasRecurring() bool {
	if o != nil && !IsNil(o.Recurring) {
		return true
	}

	return false
}

// SetRecurring gets a reference to the given bool and assigns it to the Recurring field.
func (o *QuestScheduleCreateInput) SetRecurring(v bool) {
	o.Recurring = &v
}

// GetQuestId returns the QuestId field value
func (o *QuestScheduleCreateInput) GetQuestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuestId
}

// GetQuestIdOk returns a tuple with the QuestId field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleCreateInput) GetQuestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestId, true
}

// SetQuestId sets field value
func (o *QuestScheduleCreateInput) SetQuestId(v string) {
	o.QuestId = v
}

// GetEndTime returns the EndTime field value
func (o *QuestScheduleCreateInput) GetEndTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleCreateInput) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *QuestScheduleCreateInput) SetEndTime(v time.Time) {
	o.EndTime = v
}

// GetStartTime returns the StartTime field value
func (o *QuestScheduleCreateInput) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleCreateInput) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *QuestScheduleCreateInput) SetStartTime(v time.Time) {
	o.StartTime = v
}

func (o QuestScheduleCreateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuestScheduleCreateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Recurring) {
		toSerialize["recurring"] = o.Recurring
	}
	toSerialize["questId"] = o.QuestId
	toSerialize["endTime"] = o.EndTime
	toSerialize["startTime"] = o.StartTime
	return toSerialize, nil
}

func (o *QuestScheduleCreateInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"questId",
		"endTime",
		"startTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuestScheduleCreateInput := _QuestScheduleCreateInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuestScheduleCreateInput)

	if err != nil {
		return err
	}

	*o = QuestScheduleCreateInput(varQuestScheduleCreateInput)

	return err
}

type NullableQuestScheduleCreateInput struct {
	value *QuestScheduleCreateInput
	isSet bool
}

func (v NullableQuestScheduleCreateInput) Get() *QuestScheduleCreateInput {
	return v.value
}

func (v *NullableQuestScheduleCreateInput) Set(val *QuestScheduleCreateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableQuestScheduleCreateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableQuestScheduleCreateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuestScheduleCreateInput(val *QuestScheduleCreateInput) *NullableQuestScheduleCreateInput {
	return &NullableQuestScheduleCreateInput{value: val, isSet: true}
}

func (v NullableQuestScheduleCreateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuestScheduleCreateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


