/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LeaderboardCreateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeaderboardCreateInput{}

// LeaderboardCreateInput struct for LeaderboardCreateInput
type LeaderboardCreateInput struct {
	ImageUrl *string `json:"imageUrl,omitempty"`
	Description *string `json:"description,omitempty"`
	AltScoreTextAlias *string `json:"altScoreTextAlias,omitempty"`
	ScoreTextAlias string `json:"scoreTextAlias"`
	Title string `json:"title"`
}

type _LeaderboardCreateInput LeaderboardCreateInput

// NewLeaderboardCreateInput instantiates a new LeaderboardCreateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeaderboardCreateInput(scoreTextAlias string, title string) *LeaderboardCreateInput {
	this := LeaderboardCreateInput{}
	this.ScoreTextAlias = scoreTextAlias
	this.Title = title
	return &this
}

// NewLeaderboardCreateInputWithDefaults instantiates a new LeaderboardCreateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeaderboardCreateInputWithDefaults() *LeaderboardCreateInput {
	this := LeaderboardCreateInput{}
	return &this
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *LeaderboardCreateInput) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeaderboardCreateInput) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *LeaderboardCreateInput) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *LeaderboardCreateInput) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *LeaderboardCreateInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeaderboardCreateInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *LeaderboardCreateInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *LeaderboardCreateInput) SetDescription(v string) {
	o.Description = &v
}

// GetAltScoreTextAlias returns the AltScoreTextAlias field value if set, zero value otherwise.
func (o *LeaderboardCreateInput) GetAltScoreTextAlias() string {
	if o == nil || IsNil(o.AltScoreTextAlias) {
		var ret string
		return ret
	}
	return *o.AltScoreTextAlias
}

// GetAltScoreTextAliasOk returns a tuple with the AltScoreTextAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LeaderboardCreateInput) GetAltScoreTextAliasOk() (*string, bool) {
	if o == nil || IsNil(o.AltScoreTextAlias) {
		return nil, false
	}
	return o.AltScoreTextAlias, true
}

// HasAltScoreTextAlias returns a boolean if a field has been set.
func (o *LeaderboardCreateInput) HasAltScoreTextAlias() bool {
	if o != nil && !IsNil(o.AltScoreTextAlias) {
		return true
	}

	return false
}

// SetAltScoreTextAlias gets a reference to the given string and assigns it to the AltScoreTextAlias field.
func (o *LeaderboardCreateInput) SetAltScoreTextAlias(v string) {
	o.AltScoreTextAlias = &v
}

// GetScoreTextAlias returns the ScoreTextAlias field value
func (o *LeaderboardCreateInput) GetScoreTextAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ScoreTextAlias
}

// GetScoreTextAliasOk returns a tuple with the ScoreTextAlias field value
// and a boolean to check if the value has been set.
func (o *LeaderboardCreateInput) GetScoreTextAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScoreTextAlias, true
}

// SetScoreTextAlias sets field value
func (o *LeaderboardCreateInput) SetScoreTextAlias(v string) {
	o.ScoreTextAlias = v
}

// GetTitle returns the Title field value
func (o *LeaderboardCreateInput) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *LeaderboardCreateInput) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *LeaderboardCreateInput) SetTitle(v string) {
	o.Title = v
}

func (o LeaderboardCreateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeaderboardCreateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ImageUrl) {
		toSerialize["imageUrl"] = o.ImageUrl
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.AltScoreTextAlias) {
		toSerialize["altScoreTextAlias"] = o.AltScoreTextAlias
	}
	toSerialize["scoreTextAlias"] = o.ScoreTextAlias
	toSerialize["title"] = o.Title
	return toSerialize, nil
}

func (o *LeaderboardCreateInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scoreTextAlias",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLeaderboardCreateInput := _LeaderboardCreateInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLeaderboardCreateInput)

	if err != nil {
		return err
	}

	*o = LeaderboardCreateInput(varLeaderboardCreateInput)

	return err
}

type NullableLeaderboardCreateInput struct {
	value *LeaderboardCreateInput
	isSet bool
}

func (v NullableLeaderboardCreateInput) Get() *LeaderboardCreateInput {
	return v.value
}

func (v *NullableLeaderboardCreateInput) Set(val *LeaderboardCreateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableLeaderboardCreateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableLeaderboardCreateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeaderboardCreateInput(val *LeaderboardCreateInput) *NullableLeaderboardCreateInput {
	return &NullableLeaderboardCreateInput{value: val, isSet: true}
}

func (v NullableLeaderboardCreateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeaderboardCreateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


