/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt{}

// PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt From T, pick a set of properties whose keys are in the union K
type PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt struct {
	Quantity *float64 `json:"quantity,omitempty"`
	RewardPlace float64 `json:"rewardPlace"`
	LeaderboardScheduleId string `json:"leaderboardScheduleId"`
	ProductId string `json:"productId"`
}

type _PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt

// NewPickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt instantiates a new PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt(rewardPlace float64, leaderboardScheduleId string, productId string) *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt {
	this := PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt{}
	this.RewardPlace = rewardPlace
	this.LeaderboardScheduleId = leaderboardScheduleId
	this.ProductId = productId
	return &this
}

// NewPickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAtWithDefaults instantiates a new PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAtWithDefaults() *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt {
	this := PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt{}
	return &this
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) GetQuantity() float64 {
	if o == nil || IsNil(o.Quantity) {
		var ret float64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) GetQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float64 and assigns it to the Quantity field.
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) SetQuantity(v float64) {
	o.Quantity = &v
}

// GetRewardPlace returns the RewardPlace field value
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) GetRewardPlace() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.RewardPlace
}

// GetRewardPlaceOk returns a tuple with the RewardPlace field value
// and a boolean to check if the value has been set.
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) GetRewardPlaceOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RewardPlace, true
}

// SetRewardPlace sets field value
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) SetRewardPlace(v float64) {
	o.RewardPlace = v
}

// GetLeaderboardScheduleId returns the LeaderboardScheduleId field value
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) GetLeaderboardScheduleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LeaderboardScheduleId
}

// GetLeaderboardScheduleIdOk returns a tuple with the LeaderboardScheduleId field value
// and a boolean to check if the value has been set.
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) GetLeaderboardScheduleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeaderboardScheduleId, true
}

// SetLeaderboardScheduleId sets field value
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) SetLeaderboardScheduleId(v string) {
	o.LeaderboardScheduleId = v
}

// GetProductId returns the ProductId field value
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) GetProductId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) SetProductId(v string) {
	o.ProductId = v
}

func (o PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	toSerialize["rewardPlace"] = o.RewardPlace
	toSerialize["leaderboardScheduleId"] = o.LeaderboardScheduleId
	toSerialize["productId"] = o.ProductId
	return toSerialize, nil
}

func (o *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"rewardPlace",
		"leaderboardScheduleId",
		"productId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt := _PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt)

	if err != nil {
		return err
	}

	*o = PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt(varPickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt)

	return err
}

type NullablePickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt struct {
	value *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt
	isSet bool
}

func (v NullablePickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) Get() *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt {
	return v.value
}

func (v *NullablePickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) Set(val *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) {
	v.value = val
	v.isSet = true
}

func (v NullablePickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) IsSet() bool {
	return v.isSet
}

func (v *NullablePickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt(val *PickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) *NullablePickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt {
	return &NullablePickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt{value: val, isSet: true}
}

func (v NullablePickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePickPrismaLeaderboardRewardUncheckedCreateInputExcludeKeyofPrismaLeaderboardRewardUncheckedCreateInputIdOrCreatedAtOrUpdatedAt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


