/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws{}

// PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws From T, pick a set of properties whose keys are in the union K
type PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws struct {
	Quantity *float64 `json:"quantity,omitempty"`
	ProductId string `json:"productId"`
	GoalId string `json:"goalId"`
}

type _PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws

// NewPickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws instantiates a new PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws(productId string, goalId string) *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws {
	this := PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws{}
	this.ProductId = productId
	this.GoalId = goalId
	return &this
}

// NewPickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDrawsWithDefaults instantiates a new PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDrawsWithDefaults() *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws {
	this := PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws{}
	return &this
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) GetQuantity() float64 {
	if o == nil || IsNil(o.Quantity) {
		var ret float64
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) GetQuantityOk() (*float64, bool) {
	if o == nil || IsNil(o.Quantity) {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) HasQuantity() bool {
	if o != nil && !IsNil(o.Quantity) {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given float64 and assigns it to the Quantity field.
func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) SetQuantity(v float64) {
	o.Quantity = &v
}

// GetProductId returns the ProductId field value
func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) GetProductId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProductId
}

// GetProductIdOk returns a tuple with the ProductId field value
// and a boolean to check if the value has been set.
func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) GetProductIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProductId, true
}

// SetProductId sets field value
func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) SetProductId(v string) {
	o.ProductId = v
}

// GetGoalId returns the GoalId field value
func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) GetGoalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GoalId
}

// GetGoalIdOk returns a tuple with the GoalId field value
// and a boolean to check if the value has been set.
func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) GetGoalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GoalId, true
}

// SetGoalId sets field value
func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) SetGoalId(v string) {
	o.GoalId = v
}

func (o PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Quantity) {
		toSerialize["quantity"] = o.Quantity
	}
	toSerialize["productId"] = o.ProductId
	toSerialize["goalId"] = o.GoalId
	return toSerialize, nil
}

func (o *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"productId",
		"goalId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws := _PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws)

	if err != nil {
		return err
	}

	*o = PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws(varPickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws)

	return err
}

type NullablePickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws struct {
	value *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws
	isSet bool
}

func (v NullablePickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) Get() *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws {
	return v.value
}

func (v *NullablePickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) Set(val *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) {
	v.value = val
	v.isSet = true
}

func (v NullablePickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) IsSet() bool {
	return v.isSet
}

func (v *NullablePickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws(val *PickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) *NullablePickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws {
	return &NullablePickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws{value: val, isSet: true}
}

func (v NullablePickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePickPrismaGoalProductUncheckedCreateInputExcludeKeyofPrismaGoalProductUncheckedCreateInputIdOrCreatedAtOrUpdatedAtOrUserQuestDraws) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


