/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PrismaBatchPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrismaBatchPayload{}

// PrismaBatchPayload Batch Payload for updateMany & deleteMany & createMany
type PrismaBatchPayload struct {
	Count float64 `json:"count"`
}

type _PrismaBatchPayload PrismaBatchPayload

// NewPrismaBatchPayload instantiates a new PrismaBatchPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrismaBatchPayload(count float64) *PrismaBatchPayload {
	this := PrismaBatchPayload{}
	this.Count = count
	return &this
}

// NewPrismaBatchPayloadWithDefaults instantiates a new PrismaBatchPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrismaBatchPayloadWithDefaults() *PrismaBatchPayload {
	this := PrismaBatchPayload{}
	return &this
}

// GetCount returns the Count field value
func (o *PrismaBatchPayload) GetCount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *PrismaBatchPayload) GetCountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *PrismaBatchPayload) SetCount(v float64) {
	o.Count = v
}

func (o PrismaBatchPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrismaBatchPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	return toSerialize, nil
}

func (o *PrismaBatchPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrismaBatchPayload := _PrismaBatchPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPrismaBatchPayload)

	if err != nil {
		return err
	}

	*o = PrismaBatchPayload(varPrismaBatchPayload)

	return err
}

type NullablePrismaBatchPayload struct {
	value *PrismaBatchPayload
	isSet bool
}

func (v NullablePrismaBatchPayload) Get() *PrismaBatchPayload {
	return v.value
}

func (v *NullablePrismaBatchPayload) Set(val *PrismaBatchPayload) {
	v.value = val
	v.isSet = true
}

func (v NullablePrismaBatchPayload) IsSet() bool {
	return v.isSet
}

func (v *NullablePrismaBatchPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrismaBatchPayload(val *PrismaBatchPayload) *NullablePrismaBatchPayload {
	return &NullablePrismaBatchPayload{value: val, isSet: true}
}

func (v NullablePrismaBatchPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrismaBatchPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


