/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GoalUpdateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GoalUpdateInput{}

// GoalUpdateInput struct for GoalUpdateInput
type GoalUpdateInput struct {
	BannerUrl *string `json:"bannerUrl,omitempty"`
	Instructions *string `json:"instructions,omitempty"`
	Description *string `json:"description,omitempty"`
	ActivityId string `json:"activityId"`
	QuestId string `json:"questId"`
	Target float64 `json:"target"`
	Title string `json:"title"`
	GoalId string `json:"goalId"`
}

type _GoalUpdateInput GoalUpdateInput

// NewGoalUpdateInput instantiates a new GoalUpdateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoalUpdateInput(activityId string, questId string, target float64, title string, goalId string) *GoalUpdateInput {
	this := GoalUpdateInput{}
	this.ActivityId = activityId
	this.QuestId = questId
	this.Target = target
	this.Title = title
	this.GoalId = goalId
	return &this
}

// NewGoalUpdateInputWithDefaults instantiates a new GoalUpdateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoalUpdateInputWithDefaults() *GoalUpdateInput {
	this := GoalUpdateInput{}
	return &this
}

// GetBannerUrl returns the BannerUrl field value if set, zero value otherwise.
func (o *GoalUpdateInput) GetBannerUrl() string {
	if o == nil || IsNil(o.BannerUrl) {
		var ret string
		return ret
	}
	return *o.BannerUrl
}

// GetBannerUrlOk returns a tuple with the BannerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoalUpdateInput) GetBannerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.BannerUrl) {
		return nil, false
	}
	return o.BannerUrl, true
}

// HasBannerUrl returns a boolean if a field has been set.
func (o *GoalUpdateInput) HasBannerUrl() bool {
	if o != nil && !IsNil(o.BannerUrl) {
		return true
	}

	return false
}

// SetBannerUrl gets a reference to the given string and assigns it to the BannerUrl field.
func (o *GoalUpdateInput) SetBannerUrl(v string) {
	o.BannerUrl = &v
}

// GetInstructions returns the Instructions field value if set, zero value otherwise.
func (o *GoalUpdateInput) GetInstructions() string {
	if o == nil || IsNil(o.Instructions) {
		var ret string
		return ret
	}
	return *o.Instructions
}

// GetInstructionsOk returns a tuple with the Instructions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoalUpdateInput) GetInstructionsOk() (*string, bool) {
	if o == nil || IsNil(o.Instructions) {
		return nil, false
	}
	return o.Instructions, true
}

// HasInstructions returns a boolean if a field has been set.
func (o *GoalUpdateInput) HasInstructions() bool {
	if o != nil && !IsNil(o.Instructions) {
		return true
	}

	return false
}

// SetInstructions gets a reference to the given string and assigns it to the Instructions field.
func (o *GoalUpdateInput) SetInstructions(v string) {
	o.Instructions = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GoalUpdateInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoalUpdateInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GoalUpdateInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GoalUpdateInput) SetDescription(v string) {
	o.Description = &v
}

// GetActivityId returns the ActivityId field value
func (o *GoalUpdateInput) GetActivityId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ActivityId
}

// GetActivityIdOk returns a tuple with the ActivityId field value
// and a boolean to check if the value has been set.
func (o *GoalUpdateInput) GetActivityIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ActivityId, true
}

// SetActivityId sets field value
func (o *GoalUpdateInput) SetActivityId(v string) {
	o.ActivityId = v
}

// GetQuestId returns the QuestId field value
func (o *GoalUpdateInput) GetQuestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuestId
}

// GetQuestIdOk returns a tuple with the QuestId field value
// and a boolean to check if the value has been set.
func (o *GoalUpdateInput) GetQuestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestId, true
}

// SetQuestId sets field value
func (o *GoalUpdateInput) SetQuestId(v string) {
	o.QuestId = v
}

// GetTarget returns the Target field value
func (o *GoalUpdateInput) GetTarget() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *GoalUpdateInput) GetTargetOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *GoalUpdateInput) SetTarget(v float64) {
	o.Target = v
}

// GetTitle returns the Title field value
func (o *GoalUpdateInput) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *GoalUpdateInput) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *GoalUpdateInput) SetTitle(v string) {
	o.Title = v
}

// GetGoalId returns the GoalId field value
func (o *GoalUpdateInput) GetGoalId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GoalId
}

// GetGoalIdOk returns a tuple with the GoalId field value
// and a boolean to check if the value has been set.
func (o *GoalUpdateInput) GetGoalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GoalId, true
}

// SetGoalId sets field value
func (o *GoalUpdateInput) SetGoalId(v string) {
	o.GoalId = v
}

func (o GoalUpdateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GoalUpdateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BannerUrl) {
		toSerialize["bannerUrl"] = o.BannerUrl
	}
	if !IsNil(o.Instructions) {
		toSerialize["instructions"] = o.Instructions
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["activityId"] = o.ActivityId
	toSerialize["questId"] = o.QuestId
	toSerialize["target"] = o.Target
	toSerialize["title"] = o.Title
	toSerialize["goalId"] = o.GoalId
	return toSerialize, nil
}

func (o *GoalUpdateInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"activityId",
		"questId",
		"target",
		"title",
		"goalId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGoalUpdateInput := _GoalUpdateInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGoalUpdateInput)

	if err != nil {
		return err
	}

	*o = GoalUpdateInput(varGoalUpdateInput)

	return err
}

type NullableGoalUpdateInput struct {
	value *GoalUpdateInput
	isSet bool
}

func (v NullableGoalUpdateInput) Get() *GoalUpdateInput {
	return v.value
}

func (v *NullableGoalUpdateInput) Set(val *GoalUpdateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableGoalUpdateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableGoalUpdateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoalUpdateInput(val *GoalUpdateInput) *NullableGoalUpdateInput {
	return &NullableGoalUpdateInput{value: val, isSet: true}
}

func (v NullableGoalUpdateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoalUpdateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


