/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the QuestScheduleDetailed type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuestScheduleDetailed{}

// QuestScheduleDetailed struct for QuestScheduleDetailed
type QuestScheduleDetailed struct {
	QuestId string `json:"questId"`
	Processed bool `json:"processed"`
	Recurring bool `json:"recurring"`
	EndTime NullableTime `json:"endTime"`
	StartTime time.Time `json:"startTime"`
	UpdatedAt time.Time `json:"updatedAt"`
	CreatedAt time.Time `json:"createdAt"`
	Id string `json:"id"`
	Quest Quest `json:"quest"`
}

type _QuestScheduleDetailed QuestScheduleDetailed

// NewQuestScheduleDetailed instantiates a new QuestScheduleDetailed object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuestScheduleDetailed(questId string, processed bool, recurring bool, endTime NullableTime, startTime time.Time, updatedAt time.Time, createdAt time.Time, id string, quest Quest) *QuestScheduleDetailed {
	this := QuestScheduleDetailed{}
	this.QuestId = questId
	this.Processed = processed
	this.Recurring = recurring
	this.EndTime = endTime
	this.StartTime = startTime
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	this.Id = id
	this.Quest = quest
	return &this
}

// NewQuestScheduleDetailedWithDefaults instantiates a new QuestScheduleDetailed object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuestScheduleDetailedWithDefaults() *QuestScheduleDetailed {
	this := QuestScheduleDetailed{}
	return &this
}

// GetQuestId returns the QuestId field value
func (o *QuestScheduleDetailed) GetQuestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuestId
}

// GetQuestIdOk returns a tuple with the QuestId field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleDetailed) GetQuestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestId, true
}

// SetQuestId sets field value
func (o *QuestScheduleDetailed) SetQuestId(v string) {
	o.QuestId = v
}

// GetProcessed returns the Processed field value
func (o *QuestScheduleDetailed) GetProcessed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Processed
}

// GetProcessedOk returns a tuple with the Processed field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleDetailed) GetProcessedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Processed, true
}

// SetProcessed sets field value
func (o *QuestScheduleDetailed) SetProcessed(v bool) {
	o.Processed = v
}

// GetRecurring returns the Recurring field value
func (o *QuestScheduleDetailed) GetRecurring() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Recurring
}

// GetRecurringOk returns a tuple with the Recurring field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleDetailed) GetRecurringOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recurring, true
}

// SetRecurring sets field value
func (o *QuestScheduleDetailed) SetRecurring(v bool) {
	o.Recurring = v
}

// GetEndTime returns the EndTime field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *QuestScheduleDetailed) GetEndTime() time.Time {
	if o == nil || o.EndTime.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.EndTime.Get()
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *QuestScheduleDetailed) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndTime.Get(), o.EndTime.IsSet()
}

// SetEndTime sets field value
func (o *QuestScheduleDetailed) SetEndTime(v time.Time) {
	o.EndTime.Set(&v)
}

// GetStartTime returns the StartTime field value
func (o *QuestScheduleDetailed) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleDetailed) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *QuestScheduleDetailed) SetStartTime(v time.Time) {
	o.StartTime = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *QuestScheduleDetailed) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleDetailed) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *QuestScheduleDetailed) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *QuestScheduleDetailed) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleDetailed) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *QuestScheduleDetailed) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *QuestScheduleDetailed) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleDetailed) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *QuestScheduleDetailed) SetId(v string) {
	o.Id = v
}

// GetQuest returns the Quest field value
func (o *QuestScheduleDetailed) GetQuest() Quest {
	if o == nil {
		var ret Quest
		return ret
	}

	return o.Quest
}

// GetQuestOk returns a tuple with the Quest field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleDetailed) GetQuestOk() (*Quest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quest, true
}

// SetQuest sets field value
func (o *QuestScheduleDetailed) SetQuest(v Quest) {
	o.Quest = v
}

func (o QuestScheduleDetailed) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuestScheduleDetailed) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["questId"] = o.QuestId
	toSerialize["processed"] = o.Processed
	toSerialize["recurring"] = o.Recurring
	toSerialize["endTime"] = o.EndTime.Get()
	toSerialize["startTime"] = o.StartTime
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["id"] = o.Id
	toSerialize["quest"] = o.Quest
	return toSerialize, nil
}

func (o *QuestScheduleDetailed) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"questId",
		"processed",
		"recurring",
		"endTime",
		"startTime",
		"updatedAt",
		"createdAt",
		"id",
		"quest",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuestScheduleDetailed := _QuestScheduleDetailed{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuestScheduleDetailed)

	if err != nil {
		return err
	}

	*o = QuestScheduleDetailed(varQuestScheduleDetailed)

	return err
}

type NullableQuestScheduleDetailed struct {
	value *QuestScheduleDetailed
	isSet bool
}

func (v NullableQuestScheduleDetailed) Get() *QuestScheduleDetailed {
	return v.value
}

func (v *NullableQuestScheduleDetailed) Set(val *QuestScheduleDetailed) {
	v.value = val
	v.isSet = true
}

func (v NullableQuestScheduleDetailed) IsSet() bool {
	return v.isSet
}

func (v *NullableQuestScheduleDetailed) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuestScheduleDetailed(val *QuestScheduleDetailed) *NullableQuestScheduleDetailed {
	return &NullableQuestScheduleDetailed{value: val, isSet: true}
}

func (v NullableQuestScheduleDetailed) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuestScheduleDetailed) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


