/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the LeaderboardSchedule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LeaderboardSchedule{}

// LeaderboardSchedule Model LeaderboardSchedule
type LeaderboardSchedule struct {
	LeaderboardId string `json:"leaderboardId"`
	RewardsProcessed bool `json:"rewardsProcessed"`
	ScheduleProcessed bool `json:"scheduleProcessed"`
	Recurring bool `json:"recurring"`
	EndTime NullableTime `json:"endTime"`
	StartTime time.Time `json:"startTime"`
	UpdatedAt time.Time `json:"updatedAt"`
	CreatedAt time.Time `json:"createdAt"`
	Id string `json:"id"`
}

type _LeaderboardSchedule LeaderboardSchedule

// NewLeaderboardSchedule instantiates a new LeaderboardSchedule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLeaderboardSchedule(leaderboardId string, rewardsProcessed bool, scheduleProcessed bool, recurring bool, endTime NullableTime, startTime time.Time, updatedAt time.Time, createdAt time.Time, id string) *LeaderboardSchedule {
	this := LeaderboardSchedule{}
	this.LeaderboardId = leaderboardId
	this.RewardsProcessed = rewardsProcessed
	this.ScheduleProcessed = scheduleProcessed
	this.Recurring = recurring
	this.EndTime = endTime
	this.StartTime = startTime
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	this.Id = id
	return &this
}

// NewLeaderboardScheduleWithDefaults instantiates a new LeaderboardSchedule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLeaderboardScheduleWithDefaults() *LeaderboardSchedule {
	this := LeaderboardSchedule{}
	return &this
}

// GetLeaderboardId returns the LeaderboardId field value
func (o *LeaderboardSchedule) GetLeaderboardId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LeaderboardId
}

// GetLeaderboardIdOk returns a tuple with the LeaderboardId field value
// and a boolean to check if the value has been set.
func (o *LeaderboardSchedule) GetLeaderboardIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LeaderboardId, true
}

// SetLeaderboardId sets field value
func (o *LeaderboardSchedule) SetLeaderboardId(v string) {
	o.LeaderboardId = v
}

// GetRewardsProcessed returns the RewardsProcessed field value
func (o *LeaderboardSchedule) GetRewardsProcessed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RewardsProcessed
}

// GetRewardsProcessedOk returns a tuple with the RewardsProcessed field value
// and a boolean to check if the value has been set.
func (o *LeaderboardSchedule) GetRewardsProcessedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RewardsProcessed, true
}

// SetRewardsProcessed sets field value
func (o *LeaderboardSchedule) SetRewardsProcessed(v bool) {
	o.RewardsProcessed = v
}

// GetScheduleProcessed returns the ScheduleProcessed field value
func (o *LeaderboardSchedule) GetScheduleProcessed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ScheduleProcessed
}

// GetScheduleProcessedOk returns a tuple with the ScheduleProcessed field value
// and a boolean to check if the value has been set.
func (o *LeaderboardSchedule) GetScheduleProcessedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduleProcessed, true
}

// SetScheduleProcessed sets field value
func (o *LeaderboardSchedule) SetScheduleProcessed(v bool) {
	o.ScheduleProcessed = v
}

// GetRecurring returns the Recurring field value
func (o *LeaderboardSchedule) GetRecurring() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Recurring
}

// GetRecurringOk returns a tuple with the Recurring field value
// and a boolean to check if the value has been set.
func (o *LeaderboardSchedule) GetRecurringOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recurring, true
}

// SetRecurring sets field value
func (o *LeaderboardSchedule) SetRecurring(v bool) {
	o.Recurring = v
}

// GetEndTime returns the EndTime field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *LeaderboardSchedule) GetEndTime() time.Time {
	if o == nil || o.EndTime.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.EndTime.Get()
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LeaderboardSchedule) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndTime.Get(), o.EndTime.IsSet()
}

// SetEndTime sets field value
func (o *LeaderboardSchedule) SetEndTime(v time.Time) {
	o.EndTime.Set(&v)
}

// GetStartTime returns the StartTime field value
func (o *LeaderboardSchedule) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *LeaderboardSchedule) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *LeaderboardSchedule) SetStartTime(v time.Time) {
	o.StartTime = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *LeaderboardSchedule) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *LeaderboardSchedule) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *LeaderboardSchedule) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *LeaderboardSchedule) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *LeaderboardSchedule) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *LeaderboardSchedule) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *LeaderboardSchedule) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LeaderboardSchedule) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LeaderboardSchedule) SetId(v string) {
	o.Id = v
}

func (o LeaderboardSchedule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LeaderboardSchedule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["leaderboardId"] = o.LeaderboardId
	toSerialize["rewardsProcessed"] = o.RewardsProcessed
	toSerialize["scheduleProcessed"] = o.ScheduleProcessed
	toSerialize["recurring"] = o.Recurring
	toSerialize["endTime"] = o.EndTime.Get()
	toSerialize["startTime"] = o.StartTime
	toSerialize["updatedAt"] = o.UpdatedAt
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *LeaderboardSchedule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"leaderboardId",
		"rewardsProcessed",
		"scheduleProcessed",
		"recurring",
		"endTime",
		"startTime",
		"updatedAt",
		"createdAt",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLeaderboardSchedule := _LeaderboardSchedule{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLeaderboardSchedule)

	if err != nil {
		return err
	}

	*o = LeaderboardSchedule(varLeaderboardSchedule)

	return err
}

type NullableLeaderboardSchedule struct {
	value *LeaderboardSchedule
	isSet bool
}

func (v NullableLeaderboardSchedule) Get() *LeaderboardSchedule {
	return v.value
}

func (v *NullableLeaderboardSchedule) Set(val *LeaderboardSchedule) {
	v.value = val
	v.isSet = true
}

func (v NullableLeaderboardSchedule) IsSet() bool {
	return v.isSet
}

func (v *NullableLeaderboardSchedule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLeaderboardSchedule(val *LeaderboardSchedule) *NullableLeaderboardSchedule {
	return &NullableLeaderboardSchedule{value: val, isSet: true}
}

func (v NullableLeaderboardSchedule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLeaderboardSchedule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


