/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ExternalUser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExternalUser{}

// ExternalUser struct for ExternalUser
type ExternalUser struct {
	OriginalCreationDate *time.Time `json:"originalCreationDate,omitempty"`
	UserId string `json:"userId"`
	Username string `json:"username"`
}

type _ExternalUser ExternalUser

// NewExternalUser instantiates a new ExternalUser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExternalUser(userId string, username string) *ExternalUser {
	this := ExternalUser{}
	this.UserId = userId
	this.Username = username
	return &this
}

// NewExternalUserWithDefaults instantiates a new ExternalUser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExternalUserWithDefaults() *ExternalUser {
	this := ExternalUser{}
	return &this
}

// GetOriginalCreationDate returns the OriginalCreationDate field value if set, zero value otherwise.
func (o *ExternalUser) GetOriginalCreationDate() time.Time {
	if o == nil || IsNil(o.OriginalCreationDate) {
		var ret time.Time
		return ret
	}
	return *o.OriginalCreationDate
}

// GetOriginalCreationDateOk returns a tuple with the OriginalCreationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExternalUser) GetOriginalCreationDateOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OriginalCreationDate) {
		return nil, false
	}
	return o.OriginalCreationDate, true
}

// HasOriginalCreationDate returns a boolean if a field has been set.
func (o *ExternalUser) HasOriginalCreationDate() bool {
	if o != nil && !IsNil(o.OriginalCreationDate) {
		return true
	}

	return false
}

// SetOriginalCreationDate gets a reference to the given time.Time and assigns it to the OriginalCreationDate field.
func (o *ExternalUser) SetOriginalCreationDate(v time.Time) {
	o.OriginalCreationDate = &v
}

// GetUserId returns the UserId field value
func (o *ExternalUser) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ExternalUser) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ExternalUser) SetUserId(v string) {
	o.UserId = v
}

// GetUsername returns the Username field value
func (o *ExternalUser) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *ExternalUser) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *ExternalUser) SetUsername(v string) {
	o.Username = v
}

func (o ExternalUser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExternalUser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OriginalCreationDate) {
		toSerialize["originalCreationDate"] = o.OriginalCreationDate
	}
	toSerialize["userId"] = o.UserId
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *ExternalUser) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"userId",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varExternalUser := _ExternalUser{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varExternalUser)

	if err != nil {
		return err
	}

	*o = ExternalUser(varExternalUser)

	return err
}

type NullableExternalUser struct {
	value *ExternalUser
	isSet bool
}

func (v NullableExternalUser) Get() *ExternalUser {
	return v.value
}

func (v *NullableExternalUser) Set(val *ExternalUser) {
	v.value = val
	v.isSet = true
}

func (v NullableExternalUser) IsSet() bool {
	return v.isSet
}

func (v *NullableExternalUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExternalUser(val *ExternalUser) *NullableExternalUser {
	return &NullableExternalUser{value: val, isSet: true}
}

func (v NullableExternalUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExternalUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


