/*
@ledge/external-api

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ledgeapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the QuestScheduleUpdateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuestScheduleUpdateInput{}

// QuestScheduleUpdateInput struct for QuestScheduleUpdateInput
type QuestScheduleUpdateInput struct {
	Recurring bool `json:"recurring"`
	QuestId string `json:"questId"`
	EndTime time.Time `json:"endTime"`
	StartTime time.Time `json:"startTime"`
	QuestScheduleId string `json:"questScheduleId"`
}

type _QuestScheduleUpdateInput QuestScheduleUpdateInput

// NewQuestScheduleUpdateInput instantiates a new QuestScheduleUpdateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuestScheduleUpdateInput(recurring bool, questId string, endTime time.Time, startTime time.Time, questScheduleId string) *QuestScheduleUpdateInput {
	this := QuestScheduleUpdateInput{}
	this.Recurring = recurring
	this.QuestId = questId
	this.EndTime = endTime
	this.StartTime = startTime
	this.QuestScheduleId = questScheduleId
	return &this
}

// NewQuestScheduleUpdateInputWithDefaults instantiates a new QuestScheduleUpdateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuestScheduleUpdateInputWithDefaults() *QuestScheduleUpdateInput {
	this := QuestScheduleUpdateInput{}
	return &this
}

// GetRecurring returns the Recurring field value
func (o *QuestScheduleUpdateInput) GetRecurring() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Recurring
}

// GetRecurringOk returns a tuple with the Recurring field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleUpdateInput) GetRecurringOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Recurring, true
}

// SetRecurring sets field value
func (o *QuestScheduleUpdateInput) SetRecurring(v bool) {
	o.Recurring = v
}

// GetQuestId returns the QuestId field value
func (o *QuestScheduleUpdateInput) GetQuestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuestId
}

// GetQuestIdOk returns a tuple with the QuestId field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleUpdateInput) GetQuestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestId, true
}

// SetQuestId sets field value
func (o *QuestScheduleUpdateInput) SetQuestId(v string) {
	o.QuestId = v
}

// GetEndTime returns the EndTime field value
func (o *QuestScheduleUpdateInput) GetEndTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleUpdateInput) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *QuestScheduleUpdateInput) SetEndTime(v time.Time) {
	o.EndTime = v
}

// GetStartTime returns the StartTime field value
func (o *QuestScheduleUpdateInput) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleUpdateInput) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *QuestScheduleUpdateInput) SetStartTime(v time.Time) {
	o.StartTime = v
}

// GetQuestScheduleId returns the QuestScheduleId field value
func (o *QuestScheduleUpdateInput) GetQuestScheduleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.QuestScheduleId
}

// GetQuestScheduleIdOk returns a tuple with the QuestScheduleId field value
// and a boolean to check if the value has been set.
func (o *QuestScheduleUpdateInput) GetQuestScheduleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuestScheduleId, true
}

// SetQuestScheduleId sets field value
func (o *QuestScheduleUpdateInput) SetQuestScheduleId(v string) {
	o.QuestScheduleId = v
}

func (o QuestScheduleUpdateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuestScheduleUpdateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["recurring"] = o.Recurring
	toSerialize["questId"] = o.QuestId
	toSerialize["endTime"] = o.EndTime
	toSerialize["startTime"] = o.StartTime
	toSerialize["questScheduleId"] = o.QuestScheduleId
	return toSerialize, nil
}

func (o *QuestScheduleUpdateInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recurring",
		"questId",
		"endTime",
		"startTime",
		"questScheduleId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuestScheduleUpdateInput := _QuestScheduleUpdateInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuestScheduleUpdateInput)

	if err != nil {
		return err
	}

	*o = QuestScheduleUpdateInput(varQuestScheduleUpdateInput)

	return err
}

type NullableQuestScheduleUpdateInput struct {
	value *QuestScheduleUpdateInput
	isSet bool
}

func (v NullableQuestScheduleUpdateInput) Get() *QuestScheduleUpdateInput {
	return v.value
}

func (v *NullableQuestScheduleUpdateInput) Set(val *QuestScheduleUpdateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableQuestScheduleUpdateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableQuestScheduleUpdateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuestScheduleUpdateInput(val *QuestScheduleUpdateInput) *NullableQuestScheduleUpdateInput {
	return &NullableQuestScheduleUpdateInput{value: val, isSet: true}
}

func (v NullableQuestScheduleUpdateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuestScheduleUpdateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


